### PR TITLE
Use commit_sha input that is currently ignored

### PR DESCRIPTION
**Pull request by Intrepidd**
Hi

Thanks for making this, I've been looking for an action that could do this for a while.

One issue though, the commit_sha input is ignored, it will always tag the latest commit

This is untested, but better than just an issue I guess

Thanks

### CODE REVIEW

**Comment by rickstaa** [comment]
@Intrepidd Thanks a lot for bringing this to my attention! I indeed forgot something there. I will do some testing and merge it with the main branch.

**Comment by rickstaa** [comment]
@Intrepidd Very clean code. I did a quick test using the [local GitHub action runner](https://github.com/nektos/act) and it seems to work. Thanks a lot for your contribution.

**Comment by Intrepidd** [comment]
Fabulous, thanks !

**Comment by rickstaa** [comment]
@Intrepidd You patch has been released under version https://github.com/rickstaa/action-create-tag/releases/tag/v1.1.2

**Pull request merged**
